# $wallpaper_path = ~/Pictures/wallpapers/arch-grey.jpg
#
# preload = $88.3836%wallpaper_path
# wallpaper = , $wallpaper_path

# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/
wallpaper{
  monitor = # eDP-1 # if  If empty, will use this wallpaper as a fallback
  # path = ~/Pictures/wallpapers/catppuccin/bluehour.jpg
  # path = ~/Pictures/wallpapers/catppuccin/space.png
  # path = ~/Pictures/wallpapers/zladslaw-beksinski-catppuccin(upscaled).png
  path = ~/Pictures/wallpapers/zladslaw-beksinski-catppuccin2(upscaled).png
  # path = ~/Pictures/wallpapers/zladslaw-beksinski-catppuccin3(upscaled).jpg
  fit_mode = fill # Determines how to display the image. Optional and defaults to `cover`. contain|cover|tile|fill
}
splash = false

############# Catppuccin Wallpaper Collection ###################
# Check here for some really cool catppuccin wallpapers
# https://github.com/orangci/walls-catppuccin-mocha.git
