# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = JetBrains Mono
$bg_color = rgba(0, 0, 0, 1)
$fg_color = rgba(255, 255, 255, 1)
$font_color = rgba(255, 255, 255, 0.5)

general {
    hide_cursor = True
    no_fade_int = True
}

animations {
    enabled = False
}

background {
    monitor =
    text = cmd[update:1000] echo "USER: $USER"
    color = $bg_color
    # font_family = $font
}

input-field {
    monitor =
    size = 300, 50
    position = 0, -50
    halign = center
    valign = center

    font_family = $font
    font_size = 8
    font_color = $fg_color
    inner_color = rgb(0, 0, 0)
    outer_color = $font_color
    check_color = rgb(0, 255, 0)

    outline_thickness = 1
    rounding = 0

    dots_size = 0.15
    dots_spacing = 0.5
    dots_center = true

    fade_on_empty = false
    placeholder_text = 
    font_family = $font
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = $font_color
    font_family = $font
    font_size = 64

    position = -30,0
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # updates every 60 seconds
    color = $font_color
    font_size = 14
    font_family = $font

    position = -30,-100
    halign = right
    valign = top
}
