#############
### INPUT ###
#############

# https://wiki.hypr.land/0.54.0/Configuring/Basics/Variables/#input
input {
  kb_layout = br
  kb_variant = thinkpad
  kb_model =
  kb_options =
  kb_rules =
  numlock_by_default = true

  follow_mouse = 1

  touchpad {
    natural_scroll = true
    scroll_factor = 0.3
    disable_while_typing	= true
  }

  touchdevice {
    enabled = true
  }
}

# Example per-device config
# See https://wiki.hypr.land/0.54.0/Configuring/Basics/Variables/#per-device-input-config for more
device {
  name = pixart-dell-ms116-usb-optical-mouse
  sensitivity = -0.6
  accel_profile = "flat"
}
